language: python

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install python-apt python-setuptools python-distutils-extra

install:
  - pip install pylint
  - pip install ansible
  - pip install python-apt

script: pylint apt_query.py
